# apiVersion: 1
# deleteRules:
#   - orgId: 1
#     uid: "staleness-all-fridges"
#   - orgId: 1
#     uid: "dodo-mxc-high"
#   - orgId: 1
#     uid: "staleness-dodo"
#   - orgId: 1
#     uid: "manny-mxc-high"
