apiVersion: 1

policies:
  - orgId: 1
    receiver: lab-email
    group_by: ['alertname', 'fridge']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: lab-slack
        continue: true
        matchers:
          - severity =~ "critical|warning"
      - receiver: lab-email
        matchers:
          - severity =~ "critical|warning"
